services:
  tg_bot:
    build: ./faqAI-bot
    env_file:
      - ./faqAI-bot/.env
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network

  backend:
    build: ./faqAI-back
    env_file:
      - ./faqAI-back/.env
    ports:
     - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./ai-chat
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - app-network
    ports:
      - "8080:80"

networks:
  app-network:
